### ISSUE TITLE
Create a XCMailr plugin for Neodymium

### ISSUE THREAD

**Issue by occupant23** [Xceptance/neodymium-library#120]
Please create a plugin to use XCMailr to receive test emails.
Build up the plugin and documentation similar to the  Applitools plugin (https://github.com/Xceptance/neodymium-plugin-applitools)

### Tasks
- [x] create a repository for it "neodymium-plugin-xcmailr" ask @rschwietzke for help
- [x] if not already acquired ask @jseng92 to provide an example implementation from a customer project
- [ ] create issues within the new repository to track your work like
  - [x] basic implementation
  - [x] create README to provide Getting Started information
  - [ ] deploy the plugin to Maven Central (Sonatype) ask @jowerner for guidance and credentials
  - [x] documentation in neodymium wiki
  - [ ] demo the plugin (https://github.com/Xceptance/neodymium-showcase/issues/11)

### Further work 
- [ ] create issues for further useful  functionalities around this topic
- [ ] ask @rklehm-xc if more features are required for this
- [x] create an issue in the repo to update the plugin once XCMailr is released and deployed with the new API version

**Comment by oomelianchuk** [comment]
Currently, the plugin is deployed on Maven Central as Snapshot, as soon as it will be ready for use, the deployment repository should be changed to public.
