### ISSUE TITLE
Bug: Screenresolution vs. Browserresolution

### ISSUE THREAD

**Issue by wurzelkuchen** [Xceptance/neodymium-library#312]
## Quick Description ##
We had a request, about our browse config property screenresolution. In the example config we provide examples which use screenresolution instead of browserresolution. This leads to the confusing issue, that the browser starts in default size without any notification. Also our documentation on this property is not very herlpfull.

## Actual Behaviour ##
If I use a browser config from the examples it should size the browser as configured.

## Expected Behaviour ##
Some browser configs from our browser.properties are using default values instead of the expected values due to wrongfully used keywords.

## Tasks ##

- [ ] Clean up browser.proerties and use the correct browserresolution configs
- [ ] Improve documentation (especially inside the browser.properties) and make clear, that screenresolution is only valid for emulation envorinments like browserstack
- [ ] Check our example test suites, and fix/improve the browser.properties there as well if needed
